apiVersion: v1
appVersion: 0.27.1
description: Victoria Metrics Operator
name: victoria-metrics-operator
home: https://github.com/VictoriaMetrics/operator
sources:
- https://github.com/VictoriaMetrics/helm-charts
- https://github.com/VictoriaMetrics/operator
version: 0.12.1
